/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SqlInjection;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hoef
 */
public class SqlInjection extends javax.swing.JFrame {

    private boolean do_mysql = false;
    private boolean do_oracle = true;

    /**
     * Creates new form SqlInjection
     */
    public SqlInjection() {
        initComponents();
    }

    public String makeConnectionString() {
            String host = this.jTextField_host.getText();
            String connStr = null;
            
            // Mit MySql verbinden
            if (this.do_mysql) {
                connStr = "jdbc:mysql://" + host + "/scott";
                // z.B jdbc:mysql://mysql.htl-donaustadt.at/scott
            }
            // Mit oracle verbinden
            if (this.do_oracle) {
                connStr = "jdbc:oracle:thin:@" + host + ":1521:XE";
                // jdbc:oracle:thin:@oracledb.htl-donaustadt.at:1521:XE
            }
        return connStr;
    }
    
    public void ausgeben(ResultSet rs) throws SQLException {

        String str;
        ArrayList list = new ArrayList();
        str = "";
        for (int i = 1; i <= rs.getMetaData().getColumnCount(); i++) {
            if (i > 1) {
                str += ", ";
            }
            str += rs.getMetaData().getColumnLabel(i);
        }
        System.out.println(str);

        DefaultTableModel model = (DefaultTableModel) this.jTable_select.getModel();
        model.setRowCount(0);

        rs.getMetaData().getColumnCount();
        while (rs.next()) {
            str = "";
            list.clear();
            for (int i = 1; i <= rs.getMetaData().getColumnCount(); i++) {
                if (i > 1) {
                    str += ", ";
                }
                str += rs.getString(i);
                list.add(rs.getString(i));
            }

            System.out.println(str);
            model.addRow(list.toArray());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_DB_hersteller = new javax.swing.ButtonGroup();
        jButton_exec_sql = new javax.swing.JButton();
        jRadioButton_mysql = new javax.swing.JRadioButton();
        jRadioButton_oracle = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_ename = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_select = new javax.swing.JTable();
        jTextField_host = new javax.swing.JTextField();
        jButton_prepared = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_select = new javax.swing.JTextArea();
        jButton_inject1 = new javax.swing.JButton();
        jButton_inject2 = new javax.swing.JButton();
        jButton_inject3 = new javax.swing.JButton();
        jLabel_connString = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_error = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_exec_sql.setText("Exec SQL");
        jButton_exec_sql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exec_sqlActionPerformed(evt);
            }
        });

        buttonGroup_DB_hersteller.add(jRadioButton_mysql);
        jRadioButton_mysql.setText("mySql");
        jRadioButton_mysql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_mysqlActionPerformed(evt);
            }
        });

        buttonGroup_DB_hersteller.add(jRadioButton_oracle);
        jRadioButton_oracle.setSelected(true);
        jRadioButton_oracle.setText("Oracle");
        jRadioButton_oracle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_oracleActionPerformed(evt);
            }
        });

        jLabel1.setText("Eingabe für Ename:");
        jLabel1.setToolTipText("");

        jTextArea_ename.setColumns(20);
        jTextArea_ename.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea_ename.setRows(5);
        jTextArea_ename.setText("JONES");
        jScrollPane1.setViewportView(jTextArea_ename);

        jTable_select.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "empno", "ename", "job", "sal", "comm", "sal_comm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_select);

        jTextField_host.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_host.setText("oracledb.htl-donaustadt.at");

        jButton_prepared.setText("Prepared");
        jButton_prepared.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_preparedActionPerformed(evt);
            }
        });

        jTextArea_select.setColumns(20);
        jTextArea_select.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea_select.setRows(5);
        jTextArea_select.setText("SELECT");
        jScrollPane2.setViewportView(jTextArea_select);

        jButton_inject1.setText("inject1");
        jButton_inject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_inject1ActionPerformed(evt);
            }
        });

        jButton_inject2.setText("inject2");
        jButton_inject2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_inject2ActionPerformed(evt);
            }
        });

        jButton_inject3.setText("inject3");
        jButton_inject3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_inject3ActionPerformed(evt);
            }
        });

        jLabel_connString.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_connString.setText("Connection String");

        jTextArea_error.setColumns(20);
        jTextArea_error.setRows(5);
        jScrollPane4.setViewportView(jTextArea_error);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton_mysql)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_oracle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_exec_sql)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_prepared)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_inject1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_inject2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_inject3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(jTextField_host, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_connString, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_mysql)
                    .addComponent(jRadioButton_oracle)
                    .addComponent(jButton_exec_sql)
                    .addComponent(jButton_prepared)
                    .addComponent(jButton_inject1)
                    .addComponent(jButton_inject2)
                    .addComponent(jButton_inject3)
                    .addComponent(jTextField_host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_connString))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_mysqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_mysqlActionPerformed
        do_mysql = this.jRadioButton_mysql.isSelected();
        do_oracle = this.jRadioButton_oracle.isSelected();
    }//GEN-LAST:event_jRadioButton_mysqlActionPerformed

    private void jButton_exec_sqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exec_sqlActionPerformed
        Connection conn = null;
        String connStr;
        Statement stmt;
        ResultSet rs;
        String sql;
        String eingabe;

        try {
            connStr = this.makeConnectionString();
            this.jTextArea_error.setText("");
            this.jLabel_connString.setText(connStr);
            eingabe = this.jTextArea_ename.getText();

            conn = DriverManager.getConnection(connStr, "scott", "scott");
 
            // einfaches Statement
            stmt = conn.createStatement();
            sql = "SELECT empno, ename, job, mgr, sal, COALESCE(comm,3) \n"
                + "FROM emp WHERE deptno = 20 and ename like '" + eingabe + "'";

            rs = stmt.executeQuery(sql);

            ausgeben(rs);

            this.jTextArea_select.setText(sql);
            System.out.println("SQL:" + sql);

        } catch (SQLException ex) {
            this.jTextArea_error.setText(
                    "SQLException: " + ex.getMessage()
                    +"SQLState: " + ex.getSQLState()+"\n"
                    +"VendorError: " + ex.getErrorCode());
            // handle any errors
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton_exec_sqlActionPerformed

    private void jRadioButton_oracleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_oracleActionPerformed
        do_mysql = this.jRadioButton_mysql.isSelected();
        do_oracle = this.jRadioButton_oracle.isSelected();
    }//GEN-LAST:event_jRadioButton_oracleActionPerformed

    private void jButton_preparedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_preparedActionPerformed
        String connStr;
        Connection conn = null;
        PreparedStatement prep;
        String sql;
        String eingabe;
        ResultSet rs;
        try {
            connStr = this.makeConnectionString();
            this.jTextArea_error.setText("");
            this.jLabel_connString.setText(connStr);
            eingabe = this.jTextArea_ename.getText();

            conn = DriverManager.getConnection(connStr, "scott", "scott");

            sql = "SELECT empno, ename, job, mgr, sal, COALESCE(comm,3) \n"
                    + "FROM emp WHERE deptno = ? and ename like ?";
            prep = conn.prepareStatement(sql);
            prep.setInt(1, 20);  // 1 .. erstes Fragezeichen
            prep.setString(2, eingabe);  // 2 .. zweites Fragezeichen

            rs = prep.executeQuery();

            ausgeben(rs);

            this.jTextArea_select.setText(sql);
            System.out.println("SQL:" + sql);

        } catch (SQLException ex) {
            // handle any errors
            this.jTextArea_error.setText(
                    "SQLException: " + ex.getMessage()+"\n"
                    +"SQLState: " + ex.getSQLState()+"\n"
                    +"VendorError: " + ex.getErrorCode());
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        }
    }//GEN-LAST:event_jButton_preparedActionPerformed

    private void jButton_inject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_inject1ActionPerformed
        this.jTextArea_ename.setText("' or 1='1");
    }//GEN-LAST:event_jButton_inject1ActionPerformed

    private void jButton_inject2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_inject2ActionPerformed
        this.jTextArea_ename.setText("X' ; \nselect * from dept where 'a'='a");

    }//GEN-LAST:event_jButton_inject2ActionPerformed

    private void jButton_inject3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_inject3ActionPerformed
        this.jTextArea_ename.setText("X' UNION\n"
                + "SELECT deptno, dname, loc, 1, 2, 3 from dept where 'a'='a");
    }//GEN-LAST:event_jButton_inject3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SqlInjection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SqlInjection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SqlInjection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SqlInjection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SqlInjection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_DB_hersteller;
    private javax.swing.JButton jButton_exec_sql;
    private javax.swing.JButton jButton_inject1;
    private javax.swing.JButton jButton_inject2;
    private javax.swing.JButton jButton_inject3;
    private javax.swing.JButton jButton_prepared;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_connString;
    private javax.swing.JRadioButton jRadioButton_mysql;
    private javax.swing.JRadioButton jRadioButton_oracle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_select;
    private javax.swing.JTextArea jTextArea_ename;
    private javax.swing.JTextArea jTextArea_error;
    private javax.swing.JTextArea jTextArea_select;
    private javax.swing.JTextField jTextField_host;
    // End of variables declaration//GEN-END:variables
}
